// demoData.js
export const demoProducts = [
    { id: "demo_1", name: "කාබනික එළවළු කූඩය (Organic Vegetable Pack)", cat: "Foods", price: "2500", desc: "ගෙවත්තෙන් නෙලාගත් නැවුම්, වස විසෙන් තොර එළවළු වර්ග 8ක් අඩංගුයි.", neg: true, views: 142, status: "available", shopName: "නැවුම් එළවළු අලෙවිසැල", phone: "0771234561", province: "Western", district: "Colombo", town: "Maharagama" },
    { id: "demo_2", name: "අතින් වියන ලද බට පලස් (Handmade Reed Mats)", cat: "Clothing", price: "1800", desc: "දේශීය පන් සහ බට උපයෝගී කරගෙන සාම්ප්‍රදායික ක්‍රමයට වියන ලද පැදුරු.", neg: false, views: 98, status: "available", shopName: "හෙළ පියස දේශීය නිෂ්පාදන", phone: "0719876542", province: "North Western", district: "Kurunegala", town: "Kuliyapitiya" },
    { id: "demo_3", name: "පිරිසිදු කිතුල් පැණิ (Pure Kithul Treacle - 750ml)", cat: "Foods", price: "1650", desc: "දෙණියාය රක්ෂිතාශ්‍රිත කිතුල් ගස් වලින් ලබාගත් 100% පිරිසිදු කිතුල් පැණි.", neg: false, views: 230, status: "available", shopName: "රුහුණු කිතුල් නිෂ්පාදන", phone: "0765432103", province: "Southern", district: "Matara", town: "Deniyaya" },
    { id: "demo_4", name: "ස්වභාවික සුවඳ සබන් එකතුව (Natural Herbal Soap Pack)", cat: "Clothing", price: "950", desc: "කහ, වෙනිවැල්ගැට සහ සැවැන්දරා අඩංගු සම පැහැපත් කරන ස්වභාවික සබන් වර්ග 3ක්.", neg: false, views: 64, status: "available", shopName: "ඕලු ආයුර්වේද නිෂ්පාදන", phone: "0701122334", province: "Central", district: "Kandy", town: "Peradeniya" },
    { id: "demo_5", name: "ලීයෙන් නිමවූ අලි රූප (Handcrafted Wooden Elephant)", cat: "Electronics", price: "4500", desc: "කළුදුනු ලීයෙන් සියුම්ව කැටයම් කරන ලද අඟල් 8ක අලි රූපයක්. නිවස අලංකාරයට කදිමයි.", neg: true, views: 112, status: "available", shopName: "තිසර කැටයම් ශිල්පීන්", phone: "0723344556", province: "Central", district: "Matale", town: "Dambulla" },
    { id: "demo_6", name: "දේශීය කුළුබඩු කට්ටලය (Sri Lankan Spices Mega Pack)", cat: "Foods", price: "3200", desc: "ගම්මිරිස්, කරාබුනැටි, කුරුඳු සහ සාදික්කා ඇතුළු පිරිසිදු කුළුබඩු 6ක එකතුවක්.", neg: false, views: 185, status: "available", shopName: "කුළුබඩු ලෝකය", phone: "0774455667", province: "Sabaragamuwa", district: "Kegalle", town: "Mawanella" },
    { id: "demo_7", name: "අතින් මැසූ බතික් සාරිය (Handmade Batik Saree)", cat: "Clothing", price: "8500", desc: "උසස් තත්ත්වයේ කපු රෙද්දෙන් නිමවූ, සේදිය හැකි අලංකාර බතික් සාරියක්.", neg: true, views: 310, status: "available", shopName: "සිල්ක් සහ බතික් නිවස", phone: "0759988776", province: "North Western", district: "Puttalam", town: "Marawila" },
    { id: "demo_8", name: "ස්මාර්ට් බල්බ අළුත්වැඩියා සේවාව (LED Bulb Repairing)", cat: "Services", price: "350", desc: "ඔබේ නිවසේ කැඩුණු ඕනෑම LED බල්බයක් වගකීමක් සහිතව ඉතා අඩු මිලට සකසා දෙනු ලැබේ.", neg: false, views: 45, status: "available", shopName: "Electro Tech Solutions", phone: "0711122233", province: "Western", district: "Gampaha", town: "Kadawatha" },
    { id: "demo_9", name: "පිරිසිදු පොල්තෙල් (Pure Coconut Oil - 1L)", cat: "Foods", price: "720", desc: "हिඳින ලද, රසායනික ද්‍රව්‍ය කිසිවක් මිශ්‍ර නොකළ 100% සුදු පොල්තෙල්.", neg: false, views: 199, status: "available", shopName: "සීමන්ස් පොල්තෙල් මෝල", phone: "0778899001", province: "Western", district: "Gampaha", town: "Mirigama" },
    { id: "demo_10", name: "මැටි වළං කට්ටලය (Traditional Clay Pots Pack - 5 Pcs)", cat: "Foods", price: "1400", desc: "පිළිස්සූ, ශක්තිමත් සාම්ප්‍රදායික වෑංජන පිසින මැටි වළං 5ක කට්ටලයක්.", neg: true, views: 156, status: "available", shopName: "කැලණිය මැටි භාණ්ඩ", phone: "0762233445", province: "Western", district: "Gampaha", town: "Kelaniya" },
    { id: "demo_11", name: "දේශීය ඖෂධීය තේ පැකට් (Herbal Tea Infusions)", cat: "Foods", price: "680", desc: "බෙලිමල්, රණවරා සහ පොල්පලා අඩංගු සෞඛ්‍යාරක්ෂිත පැකට් 30ක එකතුවක්.", neg: false, views: 88, status: "available", shopName: "සුව දිවි ආයුර්වේදය", phone: "0706677889", province: "Uva", district: "Badulla", town: "Bandarawela" },
    { id: "demo_12", name: "ගෙතුම් කරන ලද ළදරු ඇඳුම් (Crochet Baby Frock)", cat: "Clothing", price: "2200", desc: "මාස 6-12 ළදරුවන් සඳහා මෘදු නූලෙන් අතින් ගෙතූ අලංකාර ගවුම් පැකට්ටුවක්.", neg: false, views: 73, status: "available", shopName: "Little Blooms Crochet", phone: "0715566778", province: "Southern", district: "Galle", town: "Ambalangoda" },
    { id: "demo_13", name: "වේවැල් පුටු කට්ටලය (Premium Cane Chair Set)", cat: "Electronics", price: "28500", desc: "නිවසේ සාලය හැඩකරන්න වගකීමක් සහිතව නිමවූ වේවැල් පුටු 2ක් සහ ටීපෝවක්.", neg: true, views: 420, status: "available", shopName: "වේවැල් ලෝකය (Cane Craft)", phone: "0773344990", province: "Western", district: "Gampaha", town: "Weweldeniya" },
    { id: "demo_14", name: "ස්වභාවික මී පැණි (100% Pure Wild Honey - 500g)", cat: "Foods", price: "2400", desc: "වැදි ජනතාව විසින් වනාන්තරයෙන් නෙලාගත් පිරිසිදු ඖෂධීය වන මී පැණි.", neg: false, views: 289, status: "available", shopName: "වැදිබිම මී පැණි සැපයුම්කරුවෝ", phone: "0784433221", province: "Eastern", district: "Ampara", town: "Mahaoya" },
    { id: "demo_15", name: "ලෙදර් පිරිමි පසුම්බි (Genuine Leather Men Wallets)", cat: "Clothing", price: "3500", desc: "දේශීය ශිල්පීන් විසින් නිම කළ, කල් පවතින 100% සැබෑ ලෙදර් පසුම්බි.", neg: false, views: 104, status: "available", shopName: "ලෙදර් ක්‍රාෆ්ට් ශ්‍රී ලංකා", phone: "0725544332", province: "Western", district: "Colombo", town: "Piliyandala" },
    { id: "demo_16", name: "ගෘහස්ථ පැලෑටි වර්ග (Indoor Plants Mix Pack)", cat: "Foods", price: "1500", desc: "නිවස ඇතුලත වාතය පිරිසිදු කරන Calathea, Snake Plant ඇතුළු පැල 4ක්.", neg: false, views: 92, status: "available", shopName: "හරිත අරණ Nursery", phone: "0716655443", province: "Southern", district: "Hambantota", town: "Tangalle" },
    { id: "demo_17", name: "පැරණි කාසි සහ මුද්දර එකතුව (Antique Coins & Stamps)", cat: "Electronics", price: "12000", desc: "ලංකාවේ බ්‍රිතාන්‍ය යුගයට අයත් දුර්ලභ පැරණි කාසි 5ක් සහ මුද්දර එකතුවක්.", neg: true, views: 340, status: "available", shopName: "ඇන්ටික් ලවර්ස්", phone: "0778811223", province: "North Central", district: "Anuradhapura", town: "Mihintale" },
    { id: "demo_18", name: "CCTV කැමරා සවිකිරීමේ සේවාව (Professional CCTV Installation)", cat: "Services", price: "4500", desc: "නිවාස සහ කඩකාමර සඳහා ඉතා විශ්වාසවන්තව සහ අඩුම මිලට CCTV සවිකරදීම.", neg: false, views: 115, status: "available", shopName: "SecureEye Security Systems", phone: "0708899776", province: "Northern", district: "Jaffna", town: "Chunnakam" },
    { id: "demo_19", name: "ගෙදර හැදූ රටකජු ටොෆි (Homemade Peanut Toffee - 500g)", cat: "Foods", price: "850", desc: "නැවුම් රටකජු සහ සීනි මිශ්‍ර කර ඉතා පිරිසිදුව නිවසේදීම සකස් කරන ලද රසවත් ටොෆි.", neg: false, views: 76, status: "available", shopName: "චතු රසකැවිලි", phone: "0761199223", province: "Uva", district: "Moneragala", town: "Wellawaya" },
    { id: "demo_20", name: "අත්කම් පිත්තල පහන් (Traditional Brass Oil Lamp)", cat: "Electronics", price: "6500", desc: "පිළිමතලාව සාම්ප්‍රදායික ශිල්පීන් විසින් නිම කරන ලද පිරිසිදු පිත්තල පහනක්.", neg: true, views: 148, status: "available", shopName: "කැන්ඩියන් බ්‍රාස් ක්‍රාෆ්ට්ස්", phone: "0712244668", province: "Central", district: "Kandy", town: "Pilimathalawa" }
];